### ISSUE TITLE
Verseny indítása CSS

### ISSUE THREAD

**Issue by Uchihagyerek** [iso88592/14szf#13]
Amikor elindítjuk a versenyt, elkezdjük bepakolni a kérdéseket, akkor nagyon ronda és átláthatatlan a behelyezett kérdések listája, ráfér egy kis stílusformázás.

**Comment by iso88592** [comment]
Ennyire telik tőlem, de konstruktív javaslatot szívesen fogadok.

**Comment by Uchihagyerek** [comment]
A gombok nagyon összefolytak, azóta jobb a helyzet, még mindig kicsit furcsa, szerintem vagy a gombok után kéne egy line-break, vagy valahogy elkülöníteni őket a feladatleírástól

![kép](https://user-images.githubusercontent.com/45459135/55388144-052c6780-5533-11e9-9365-3fec8fc79a62.png)

itt én pl egy sima br-el próbáltam ki, valami ilyesmire gondoltam

**Comment by iso88592** [comment]
Fixed. Thx.
