### ISSUE TITLE
BBcode feladat létrehozásnál nem működik

### ISSUE THREAD

**Issue by amlantir** [iso88592/14szf#16]
:'(

**Comment by JustGregHu** [comment]
.,--.
 .' __  \
 | .._  |
 |{)(} .'
 / /|  |.
(_/ /____)
  |_||
    /'
    //
  .'''\
 /\:::/\
( /|::|\\
_\:|;;|{/_
'.;|**|\;,/
   \_ /
   | ||
   | ||
   | ||
   | ||
 ._| ||_.
;,_.-._,;

**Comment by amlantir** [comment]
vaklárma
