### ISSUE TITLE
válaszolás

### ISSUE THREAD

**Issue by timi1998** [iso88592/14szf#18]
3 válaszból 1-et választattam a  jót de nem fogata el 0/20 marat végig a jó válasz ellenére

**Comment by MrAxe007** [comment]
Kiegészítés:
       A hiba CSAK felelet választós esetben áll fent.
       Ha valaki az egy válaszadós feladatot megválaszolja mindenki megkapja a pontot, de ha nem frissíti az oldalt kevesebb pontot ad

**Comment by iso88592** [comment]
Fixed, thx.
