### ISSUE TITLE
admin panel - start-stop gombok elhelyezése

### ISSUE THREAD

**Issue by cherry-412** [iso88592/14szf#24]
Verseny megkezdése után az újonnan megjelent Stop doboz helyzete nem egyezik meg a megkezdés előtt látható Start doboz helyzetével. Konzisztensebb megjelenésre van szükség

**Comment by cherry-412** [comment]
![kép](https://user-images.githubusercontent.com/36326016/55160697-350af200-5164-11e9-9e71-6091db076cc5.png)
![kép](https://user-images.githubusercontent.com/36326016/55160710-3fc58700-5164-11e9-97a1-8126825e142e.png)

**Comment by iso88592** [comment]
Fixed, thx.
