### ISSUE TITLE
#banneren belül van egy fölösleges <div>

### ISSUE THREAD

**Issue by Uchihagyerek** [iso88592/14szf#3]
a #banner kép túl széles, furcsán néz ki

**Comment by Uchihagyerek** [comment]
#banneren belül van egy fölösleges div

**Comment by cherry-412** [comment]
ezek mellett a kép tömörítése túl erős. javaslat: kép cseréje vagy a kép magasabb minőségű változatának beszerzése

**Comment by iso88592** [comment]
Fixed. Thx.
