### ISSUE TITLE
Kijelentkezés

### ISSUE THREAD

**Issue by Uchihagyerek** [iso88592/14szf#30]
#2  Kijelentkezéskor visszadob az üres kezdőlapra

**Comment by iso88592** [comment]
Igen, és ezzel mi a baj?

**Comment by Uchihagyerek** [comment]
Mivel a kezdőlap üres, akár lehetne rajta a bejelentkezés is :D vagy valamelyik felső sarokban

**Comment by iso88592** [comment]
Szerintem nem kell bejelentkezés. Végül az eredményjelzőt raktam ki a kezdőlapra.

**Comment by Uchihagyerek** [comment]
adom
