### ISSUE TITLE
Csapatok panel - gombok vízszintes középre helyezése

### ISSUE THREAD

**Issue by cherry-412** [iso88592/14szf#31]
Ha csapatként lépünk be a csapatok panelra, a jobb oldalt megjelenő gombok szövegei nem helyezettek középre vízszintesen
![kép](https://user-images.githubusercontent.com/36326016/55161532-0d1c8e00-5166-11e9-8c2a-f4351b135dfe.png)

**Comment by iso88592** [comment]
A gombon belül középre van igazítva a szöveg. A gomb a táblázathoz képest középre van igazítva. Mi nincs középre igazítva?
![image](https://user-images.githubusercontent.com/14221367/55180377-c5a7f900-5189-11e9-9d4e-cc4770248cfa.png)

**Comment by Uchihagyerek** [comment]
függőlegesen értette

**Comment by cherry-412** [comment]
^ igen

**Comment by iso88592** [comment]
Fixed. Thx.
