### ISSUE TITLE
Internet explorer 11 - néhány speciális karakter kicserélődik más betűtípusra

### ISSUE THREAD

**Issue by cherry-412** [iso88592/14szf#35]
lásd: cím.

IE: 

![kép](https://user-images.githubusercontent.com/36326016/55161629-48b75800-5166-11e9-81ba-9d80e94e5ea2.png)
![kép](https://user-images.githubusercontent.com/36326016/55161640-4d7c0c00-5166-11e9-9140-a82208a19dc6.png)

FIREFOX:

![kép](https://user-images.githubusercontent.com/36326016/55161685-65539000-5166-11e9-860b-40f8279638e3.png)
![kép](https://user-images.githubusercontent.com/36326016/55161697-6a184400-5166-11e9-9c28-dd4188f73a15.png)

**Comment by iso88592** [comment]
No IE supported. Thx.
