### ISSUE TITLE
Feladatok nehézségének beállítása

### ISSUE THREAD

**Issue by Uchihagyerek** [iso88592/14szf#36]
A 3 lehetőség S/M/L, ami nem annyira logikus, lehetne E/M/H, vagy egy olyan lehetőség, amivel meg lehet adni hány pontot ér a feladat

**Comment by starring94** [comment]
odakéne legyen írva hogy hány pontot ér

**Comment by cherry-412** [comment]
imádlak

**Comment by iso88592** [comment]
![image](https://user-images.githubusercontent.com/14221367/55179376-90021080-5187-11e9-8d9a-2d30e5a90a40.png)
Fixed. Thx.
