### ISSUE TITLE
Belépés panel - navbar nem mutatja a kiválasztott oldalt

### ISSUE THREAD

**Issue by cherry-412** [iso88592/14szf#38]
A belépés panel navbarján a "Belépés" gombnak narancssárga hátterűnek kéne lennie, mivel ezesetben az az oldal van kiválasztva.

![kép](https://user-images.githubusercontent.com/36326016/55162028-2e31ae80-5167-11e9-84c1-383b330f37cc.png)

**Comment by iso88592** [comment]
Fixed. Thx.
