### ISSUE TITLE
dupla feladatindítás

### ISSUE THREAD

**Issue by bonhart-rs** [iso88592/14szf#41]
Feladat 2 indításához az URL kimásolása után a feladat 2-vel ellátott versenyt elindítjuk.
A kimásolt URL beillesztésével visszamegyünk a feladatmegadáshoz.
Feladat megváltoztatása, majd verseny indítása.
Nem írja felül, csak 1 verseny fut.

**Comment by iso88592** [comment]
Fixed. Thx.
