### ISSUE TITLE
csapat adminisztrátor

### ISSUE THREAD

**Issue by timi1998** [iso88592/14szf#49]
csapat adminisztrátort ként kezdőlapra kattintva eltűnik az admin felület

**Comment by timi1998** [comment]
közben észrevettem, hogy a kezdőlapon a linkről elérhető ismét

**Comment by starring94** [comment]
Jobb lenne ha a menüben lenne úgy, hogy Admin helyett mondjuk Csapat lenne írva.

**Comment by iso88592** [comment]
Good as-is. Thx.
