### ISSUE TITLE
Felosztás

### ISSUE THREAD

**Issue by starring94** [iso88592/14szf#50]
Ha játékosokkal vagy válaszokkal foglalkozunk, zavaró hogy felette van a kérdéslista, még akkor is ha ledob oda hozzáadáskor. Helyette inkább vissza lehetne menni ha az kéne (szétoszani a csapatkezelést csapatkezelésre és csapatjátékos kezelésre, ugyanígy a kérdéseket és a válaszokat is).

**Comment by MrAxe007** [comment]
Szerintem nem zavaró. Inkább az a rossz, hogy versenyző megadásnál mindig rá kell a csapatra kattintani. A kérdések kezelő oldal alapján működhetne.

**Comment by starring94** [comment]
Kérdéseknél nem kell, de szerintem azért kéne mert összezavarhatja az embereket ha nem folyamatosan csinálják az egészet.

**Comment by iso88592** [comment]
Fixed. Thx.
