### ISSUE TITLE
Felhasználó létrehozás bug?

### ISSUE THREAD

**Issue by amlantir** [iso88592/14szf#55]
Nem tudom, hogy bug, vagy így akartad, de lehet csinálni felhasználót "Név" nélkül is, csak így a név alapból üres lesz.

**Comment by starring94** [comment]
Nem a felhasználónévről beszél hanem a másikról, de nem igazán van használva az semmire.

**Comment by amlantir** [comment]
Úgy értettem, hogy létre tudsz hozni usert "Név" mező megadás nélkül, amit ki is emeltem a kérdésben.

**Comment by iso88592** [comment]
Works as intended.
