### ISSUE TITLE
Felhasználónév megadás hosszúság bug

### ISSUE THREAD

**Issue by amlantir** [iso88592/14szf#58]
Ha nagyon hosszú, akkor error-t dob, de így is túl hosszút meg lehet adni, ami kilóg és elég ronda tud lenni.

**Comment by starring94** [comment]
Hasonlít #56 -ra.

**Comment by timi1998** [comment]
túl hosszú csapat név esetén az egész eltolódik balra:
![Névtelen2](https://user-images.githubusercontent.com/45600733/55390134-db753f80-5536-11e9-99bf-8b888ac0d4b9.png)

**Comment by timi1998** [comment]
erre a túllogásra gondoltál?:
![névtelen3](https://user-images.githubusercontent.com/45600733/55390255-1bd4bd80-5537-11e9-909d-b8b29a418849.png)

**Comment by amlantir** [comment]
> 
> 
> erre a túllogásra gondoltál?:
> ![névtelen3](https://user-images.githubusercontent.com/45600733/55390255-1bd4bd80-5537-11e9-909d-b8b29a418849.png)

Igen erre

**Comment by iso88592** [comment]
Fixed. Thx.
