### ISSUE TITLE
Választípus

### ISSUE THREAD

**Issue by starring94** [iso88592/14szf#59]
Ha több válasz van, de csak egy válasz jó, akkor lehetne radiogombos, vagy be lehetne állítani a kérdésnél magánál, hogy radiogombos vagy selectes (persze akkor radiogombos típusnál az adminfelületen csak egy jó válasz lehessen).

**Comment by iso88592** [comment]
A customer szerint nem kell, a versenyző ne legyen biztos benne, hogy csak egy jó van.
