### ISSUE TITLE
valasz megadas

### ISSUE THREAD

**Issue by bonhart-rs** [iso88592/14szf#8]
feladat létrehozásnál ha nincs feladat kiválasztva, meg lehet adni választ, de crashel

**Comment by iso88592** [comment]
Nem válsz létrehozásnál?

**Comment by MrAxe007** [comment]
Ha jól emlékszem, jó válasznál is előkerült a hiba. Nem válasz esetén biztosan.

**Comment by iso88592** [comment]
Fixed. Thx.
